Repository Gidsss/UwUIDE, pull requests merged in 2023-11, with the labels that each got.

#16 Reserved words checks
  example.py
  src/lexer/__main__.py
  src/lexer/error_handler.py
  src/lexer/lexer.py
  src/lexer/token.py
Labels: enhancement

#18 Manual checks
  constants/constants.py
  src/lexer/__main__.py
  src/lexer/error_handler.py
  src/lexer/lexer.py
  src/lexer/token.py
Labels: enhancement

#5 Feat/UwU IDE GUI
  assets/load.png
  assets/logo_black.png
  assets/logo_white.png
  assets/run.png
  assets/save.png
  constants/path.py
  requirements.txt
  src/components/__init__.py
  src/components/analyzer_tabs.py
  src/components/code_view.py
  src/components/command_menu.py
  src/components/console_view.py
  src/components/lexer_table.py
  src/components/logs_table.py
  src/lexer/__init__.py
  src/uwu.py
Labels: enhancement

#27 Fix bugs from: seek, is_fwunc_or_cwass_name, is_identifier, peek_int_float_literal, peek_comments, and peek_string_literals
  constants/constants.py
  src/lexer/__main__.py
  src/lexer/error_handler.py
  src/lexer/lexer.py
  src/lexer/token.py
Labels: bug, enhancement

#36 bug: unique token type missing formatting
  src/lexer/token.py
Labels: bug

#38 function name became part of data type if data type is not delimited
  src/lexer/lexer.py
Labels: bug

#45 Function and variable parsing
  constants/constants.py
  src/lexer/__main__.py
  src/lexer/error_handler.py
  src/lexer/lexer.py
  src/lexer/token.py
Labels: refactor

#49 fix renamed enum items
  src/lexer/lexer.py
  src/lexer/token.py
Labels: bug

#58 Function and variable parsing
  constants/constants.py
  src/lexer/__main__.py
  src/lexer/error_handler.py
  src/lexer/lexer.py
  src/lexer/token.py
Labels: refactor

#61 Rename delim error
  src/lexer/error_handler.py
Labels: refactor

#62 Whitespace delim for everyone
  constants/constants.py
Labels: refactor

#64 move cursor module
  .gitignore
  src/lexer/lexer.py
  src/lexer/lexer_components/move_cursor.py
  src/lexer/lexer_components/peek_id.py
  src/lexer/lexer_components/peek_int_float.py
  src/lexer/lexer_components/peek_reserved.py
  src/lexer/lexer_components/peek_string.py
  src/lexer/lexer_components/verify_delim.py
Labels: enhancement, refactor

#65 verifying delimiter module
  src/lexer/lexer.py
  src/lexer/lexer_components/verify_delim.py
Labels: enhancement, refactor

#66 reserved words/symbols + identifier and cwass name module
  src/lexer/lexer.py
  src/lexer/lexer_components/move_cursor.py
  src/lexer/lexer_components/peek.py
  src/lexer/lexer_components/peek_id.py
  src/lexer/lexer_components/peek_int_float.py
  src/lexer/lexer_components/peek_reserved.py
  src/lexer/lexer_components/peek_string.py
  src/lexer/lexer_components/verify_delim.py
Labels: enhancement, refactor

#67 comments module
  src/lexer/lexer.py
  src/lexer/lexer_components/peek.py
  src/lexer/lexer_components/seek.py
Labels: enhancement, refactor

#68 int float + string module
  src/lexer/lexer.py
  src/lexer/lexer_components/peek.py
Labels: enhancement, refactor
