Repository Gidsss/UwUIDE, pull requests merged in 2024-02, with the labels that each got.

#73 Feat/parser init
  .gitignore
  packages/uwu/main.py
  src/lexer/lexer.py
  src/lexer/token.py
  src/parser/__init__.py
  src/parser/__main__.py
  src/parser/parser.py
  src/parser/productions.py
Labels: enhancement

#81 Feat/rewrite parser
  constants/constants.py
  src/lexer/__init__.py
  src/lexer/__main__.py
  src/lexer/lexer.py
  src/lexer/lexer_components/peek.py
  src/lexer/token.py
  src/parser/__init__.py
  src/parser/__main__.py
  src/parser/parser.py
  src/parser/productions.py
Labels: enhancement

#94 Feat/parse pwint inpwt
  constants/constants.py
  src/parser/__main__.py
  src/parser/parser.py
  src/parser/productions.py
Labels: enhancement

#95 parse nuww
  src/parser/__main__.py
  src/parser/parser.py
Labels: enhancement

#96 Parse Functions
  src/parser/__main__.py
  src/parser/parser.py
  src/parser/productions.py
Labels: enhancement

#100 Refactor/printing ast
  src/lexer/token.py
  src/parser/__main__.py
  src/parser/parser.py
  src/parser/productions.py
Labels: refactor

#113 `child_nodes()` returns a dict instead of list for additional context for GUI
  src/parser/productions.py
Labels: enhancement

#115 fix: optional child nodes are now optional
  src/parser/productions.py
Labels: bug

#124 Feat/parse error returns none
  src/parser/__main__.py
  src/parser/parser.py
Labels: enhancement
